### ISSUE TITLE
Manual task ordering

### ISSUE THREAD

**Issue by SmilyFace** [philfontaine/autolaunch#11]
it is easy to add order field to task and sort task before launch, it is usefull when we want to start differenet tasks from different workspace with direct order

**Comment by philfontaine** [comment]
What tasks are you trying to launch? 
Is #12 really solving your problem? (i.e. have you tested that it does)

It seems that you want to start task A before starting B, probably because B depends on A.
I have not benchmarked the delay between each task, but it is probably very small. So, will it really make a difference in your use case? 

**Since we don't wait** for the end of a task, the order should not really make a difference. And if it does, it seems to me that it's an unpredictable race condition. 

Let me give you an example:
Let's say there is a 100ms delay between each task start.
Task A takes 50ms to complete.
Task B depends on task A.

In this case, the order could make a difference: We start Task A, which ends after 50ms. Task B starts 100ms later, and since Task A has completed, all is well.

However, lets use the same example, but Task A takes 500ms to complete. We start Task A. 100ms later, we start Task B, but task A isn't done yet, so it crashes.

Do you see my point? Am I getting your use case right?

**Comment by SmilyFace** [comment]
Let me explain my situation. I am working on a project where few tasks are running separatly in different workspaces. All my tasks are vue-cli dev server tasks for different projects, each one works on it own port(should). It one time it could be of 2 to 5 tasks launched. Each task does not depend on each other by its result, but it depends via port it takes, port should be the same each time for each task. 

Vue cli dev server takes first free port when we restart all tasks. When i restart vscode i expect launching my tasks in direct order, so, if order of workspaces and task is same - it is ok, but if more tasks appear or workspaces are mixed, i have a problem with task launch order.

Of course i can change configs of each task by setting port option but it is not good solution when you are working with teammates for some reasons.

So, #12 can be a solution. Order option gives us control over the workspaces order. And it is only option, so it should not break something. Without order option all ordering should be the same, "ordered" tasks would be after task without order option, so we can mix

**Comment by philfontaine** [comment]
vue-cli dev server is a good example that agrees with what I'm saying. I believe that the port is only assigned after webpack is done compiling. Therefore, the port order will mostly depend on the compilation time of each project, and not solely on the order it was launched. 

i.e. you could have this result:

| Task | Time to compile (ms) | Port |
| --- | --: | --- |
| A | 500 | 8081 |
| B | 400 | 8080 |

And then you could add a huge library to project B and it now takes 600ms to compile, once again changing the port order.

In my opinion, I don't think it makes sense to provide this feature, when the order is not even guaranteed to be respected and it always comes down to timing/delays/race conditions.

Also, I just realized that your specific problem could be easily fixed. Simply reorder the workspaces to the order that suits you (drag n drop). Tasks respect the order of the workspaces.

**Comment by SmilyFace** [comment]
Ordering workspaces can be a good decision, but i have seen some interesting behavior. If i close Vscode in some not first workspace and start Vscode, tasks starts from first workspace opened(where was i at closing), not first in order in Vscode panel. It is not bad, just choose first worspace and restart Vscode

Some words about running few vue cli and ports for each one.
Tasks starts each one after other in short time and each on gets about 5-30 seconds to precompile(of course they can precompile in different time, its very different big and small projects), it seems like they get their ports in the begining of task work, not at the end, because i see order of chosen ports 

All these problems can be solved with right task ordering or vscode starting but it seems to me, adding some ordering to tasks, except workspace ordering, give us more control and power. Need to notice, this all tasks ordering would work into one workspace too, and you would not need to cut and paste tasks code

**Comment by philfontaine** [comment]
I don't fully understand what your issue is, but I can tell you what this extension does:
- Loop through each workspace folder **in the order they are in the panel**
  - Loop through each task in each of these workspace, **in the order they are specified in the tasks.json**

With that said, you should be able to get the order you want by reordering the tasks or the workspace folders. If you don't get that order, then your issue is not with this extension.
