### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by Lonyless** [philfontaine/autolaunch#13]
wont work even with the most basisc script. please delete this repo

**Comment by philfontaine** [comment]
This extension is not actively maintained, mainly because most of it is now offered [directly in VS Code](https://code.visualstudio.com/updates/v1_30#_run-on-folder-open) and because there isn't much to add in terms of functionality.

However, I just tested it with the last version of VS Code and it works just fine, as it always has.

I think your comment is very rude and not justified. If you want some help, please be a little more polite. Nobody forced you to use this extension.

**Comment by Lonyless** [comment]
> I think your comment is very rude and not justified. If you want some help, please be a little more polite. Nobody forced you to use this extension.

sorry mate, just got me in a bad day
