### ISSUE TITLE
Add the possibility to be prompted before launching a task/configuration

### ISSUE THREAD

**Issue by NoriSte** [philfontaine/autolaunch#6]
After some months using (and appreciating) the extension I realized that sometimes I'd like to open a workspace just for a fast look at the code. In this case, I don't want that the tasks I configured to be launched automatically are launched. Probably they will collide with the port used by other tasks or launch lot of 'onchange' commands...

My proposal is to provide a hotkey that the extension will check when it's about to run the tasks and, if it's pressed, no tasks will be launched automatically.

What do you think?

Anyway: well done, it's a nice extension

**Comment by philfontaine** [comment]
I think it is a good idea, I will look into it when I have some spare time.

**Comment by philfontaine** [comment]
I did some tests to implement this feature. I found a way that is doable, but really not ideal. 

I delay the execution of autolaunch for a few seconds, letting some time to detect the "hotkey". However, there is a huge and inconsistent delay between the time that the extension gets activated, and the time that the "hotkey" is detected (I got from 1 second to 3 seconds). 

So, to get this feature working, I'd need to delay autolaunching for at least 3 seconds more than what it currently takes (with no guarantee that it won't take more since it probably depends on how much extension are installed).

I could put a setting to disable this feature for those who don't need it, but I'm wondering if it is worth developing at all.

Knowing that there would be a supplementary 3-5 seconds delay each time you'd want to autolaunch, would you still be interested in this feature?

**Comment by NoriSte** [comment]
I was looking for a solution myself, I'd like to make a PR in the near future... the only solution I found was to have a second shortcut that saves a flag to be read by the main script of the extension... but if you know that the extension has a significant delay in execution my idea is bad.

Anyway: thank you for your tests and I agree, adding more delay isn't a good solution. What could be fine in both situations (no additional delay and option to avoid tasks autorun) is an extension setting that can be set to
- 'auto': the default value
- 'prompt': it prompts you to know if you'd like to launch the tasks or not

What do you think? So for a basic user, nothing changes and in 'my' case I'll set the value to 'prompt'.

**Comment by philfontaine** [comment]
Sounds like a good idea, I will implement this soon, unless you have a PR in progress.

**Comment by NoriSte** [comment]
Yes I'm implementing it, I'll open a PR soon. That's my first PR so I ask you a bit of patience :)
